export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  summary: string;
  content: string;
  category: string;
  author: {
    name: string;
    avatar: string;
    role: string;
  };
  readTime: string;
  views: string;
  publishDate: string;
  imageUrl: string;
  featured: boolean;
  trending: boolean;
  tags: string[];
}

export const CATEGORIES = [
  { name: 'Carbon Footprint', icon: '👣', count: 12 },
  { name: 'Climate Change', icon: '🌍', count: 24 },
  { name: 'Renewable Energy', icon: '☀️', count: 18 },
  { name: 'Green Technology', icon: '🔋', count: 15 },
  { name: 'Waste Management', icon: '🗑️', count: 20 },
  { name: 'Recycling', icon: '♻️', count: 35 },
  { name: 'Circular Economy', icon: '🔄', count: 14 },
  { name: 'Sustainable Living', icon: '🌱', count: 42 },
  { name: 'Electric Vehicles', icon: '⚡', count: 11 },
  { name: 'Smart Cities', icon: '🏙️', count: 9 },
  { name: 'AI for Sustainability', icon: '🧠', count: 16 },
  { name: 'Environmental News', icon: '📰', count: 28 },
];

export const FACTS = [
  "Recycling one aluminum can saves enough energy to run a TV for several hours.",
  "Food waste contributes significantly to global emissions.",
  "Public transportation can dramatically reduce individual carbon impact.",
  "Only 9% of all plastic waste ever produced has been recycled.",
  "Switching to LED bulbs uses 75% less energy and lasts 25 times longer.",
  "Smart recycling machines can increase community recycling rates by up to 300%."
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    slug: 'understanding-your-carbon-footprint',
    title: 'Understanding Your Carbon Footprint',
    summary: 'Everything you need to know about measuring, tracking, and reducing your daily carbon emissions using modern tools.',
    content: `
## What is a Carbon Footprint? 

A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our actions. 

## Why it Matters 

The average carbon footprint for a person in the United States is 16 tons, one of the highest rates in the world. Globally, the average is closer to 4 tons. To have the best chance of avoiding a 2℃ rise in global temperatures, the average global carbon footprint per year needs to drop under 2 tons by 2050.

### The Breakdown of Personal Emissions
| Category | Average % of Footprint | Key Contributors |
|----------|-----------------------|------------------|
| Transportation | 28% | Cars, Flights, Public Transit |
| Housing | 26% | Electricity, Heating, Cooling |
| Food | 20% | Meat consumption, Imported goods |
| Goods & Services | 26% | Clothing, Electronics, Healthcare |

## How THADAM Helps 

With THADAM's Carbon Tracker and Carbon Twin AI, you can seamlessly monitor your daily activities. Every time you log a commute, a meal, or a recycling action using our Smart Machines, THADAM calculates the exact impact.

### 5 Ways to Reduce Your Footprint Today
1. **Switch to Renewable Energy:** Opt for a green energy provider if available in your area.
2. **Drive Less, Walk More:** Use public transportation, carpool, or switch to an electric vehicle.
3. **Eat Plant-Based:** Reducing meat consumption, especially beef, dramatically lowers emissions.
4. **Recycle Smartly:** Use THADAM Smart Machines to ensure zero-contamination recycling.
5. **Optimize Home Energy:** Install LED bulbs, smart thermostats, and proper insulation.

## FAQ
**Q: How accurate is the THADAM Carbon Tracker?**  
A: Our tracker uses advanced AI to estimate emissions based on global standards and localized data for maximum precision.

**Q: Does recycling actually help my footprint?**  
A: Absolutely. Recycling aluminum, for instance, saves 95% of the energy required to make the same amount of aluminum from its virgin source.
    `,
    category: 'Carbon Footprint',
    author: { name: 'Dr. Sarah Jenkins', avatar: 'https://i.pravatar.cc/150?u=sarah', role: 'Climate Scientist' },
    readTime: '10 min',
    views: '12.4K',
    publishDate: '2026-06-10',
    imageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&q=80',
    featured: true,
    trending: true,
    tags: ['Carbon', 'Beginner', 'Tracker']
  },
  {
    id: '2',
    slug: 'sustainable-living-for-students',
    title: 'Sustainable Living for Students',
    summary: 'Practical, budget-friendly ways for college and university students to reduce their environmental impact.',
    content: `
## The Student Impact

Campuses are micro-cities. With thousands of students consuming energy, food, and generating waste, the collective footprint is massive. However, this also means small behavioral changes scale incredibly well.

## Top Strategies for Green Dorm Life

### 1. Second-Hand Everything
From textbooks to dorm furniture, buying used not only saves money but also entirely eliminates the carbon footprint of manufacturing a new product.

### 2. Smart Energy Use
- Turn off power strips when leaving for class.
- Use natural light during the day.
- Wash clothes in cold water to save up to 90% of the energy used by washing machines.

### 3. THADAM on Campus
Many universities are now installing THADAM Smart Recycling Machines in student unions. By recycling your daily coffee cups and notes, you can earn Reward Points that can be redeemed for campus bookstore discounts.

## FAQ
**Q: Can I really make a difference as one student?**  
A: Yes. Your habits influence your peers. The ripple effect of one sustainable student can transform an entire dormitory's culture.
    `,
    category: 'Sustainable Living',
    author: { name: 'Emily Rostova', avatar: 'https://i.pravatar.cc/150?u=emily', role: 'Campus Coordinator' },
    readTime: '7 min',
    views: '8.1K',
    publishDate: '2026-06-12',
    imageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=800&q=80',
    featured: false,
    trending: true,
    tags: ['Students', 'Campus', 'Lifestyle']
  },
  {
    id: '3',
    slug: 'green-technology-innovations',
    title: 'Green Technology Innovations',
    summary: 'A look at the cutting-edge tech that is helping us clean the oceans, capture carbon, and generate infinite clean energy.',
    content: `
## The Tech Revolution in Climate Change

While human behavior must change, technology provides the leverage necessary to avert the worst climate scenarios.

### Carbon Capture and Storage (CCS)
Direct Air Capture (DAC) facilities are now actively pulling CO2 directly from the atmosphere and sequestering it deep underground, or turning it into usable products like sustainable aviation fuel.

### Ocean Cleanup Arrays
Autonomous, solar-powered vessels are currently navigating the Great Pacific Garbage Patch, utilizing AI to identify and collect tons of plastic waste before it degrades into microplastics.

### Next-Gen Batteries
Solid-state batteries promise to revolutionize energy storage by offering higher energy density, faster charging times, and greater safety compared to traditional lithium-ion batteries.

## THADAM's Technological Contribution
Our platform integrates Gemini 1.5 Pro and Vision to instantly analyze waste streams. This is micro-level green technology empowering macro-level change.
    `,
    category: 'Green Technology',
    author: { name: 'Michael Chen', avatar: 'https://i.pravatar.cc/150?u=mike', role: 'Tech Analyst' },
    readTime: '8 min',
    views: '15.2K',
    publishDate: '2026-06-13',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
    featured: true,
    trending: true,
    tags: ['Innovation', 'AI', 'Future']
  },
  {
    id: '4',
    slug: 'smart-waste-management-systems',
    title: 'Smart Waste Management Systems',
    summary: 'How IoT sensors, computer vision, and AI are transforming the way cities handle municipal solid waste.',
    content: `
## The Problem with Traditional Waste Management

Historically, waste collection has been static. Trucks run on fixed routes regardless of whether bins are full or empty, leading to unnecessary carbon emissions from the trucks and overflowing bins.

## The Smart Solution

### Fill-Level Sensors
IoT sensors placed inside bins communicate real-time fill levels to a central dashboard. Algorithms then calculate the most efficient collection route, reducing fuel consumption by up to 30%.

### Automated Sorting Facilities
Using advanced robotics and computer vision, modern Material Recovery Facilities (MRFs) can sort plastics, metals, and paper at superhuman speeds and with incredibly high purity rates.

### The THADAM Smart Machine
Our edge-computing enabled machines use Gemini Vision to identify deposited items, immediately crediting the user and sorting the material internally to prevent contamination.
    `,
    category: 'Waste Management',
    author: { name: 'David Okafor', avatar: 'https://i.pravatar.cc/150?u=david', role: 'Urban Planner' },
    readTime: '6 min',
    views: '5.4K',
    publishDate: '2026-06-08',
    imageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&q=80',
    featured: false,
    trending: false,
    tags: ['Smart Cities', 'IoT', 'Recycling']
  },
  {
    id: '5',
    slug: 'future-of-renewable-energy',
    title: 'Future of Renewable Energy',
    summary: 'Solar and wind are just the beginning. Discover the next generation of renewable energy sources powering our future.',
    content: `
## Beyond Solar and Wind

While solar photovoltaics and onshore wind dominate the renewable energy conversation, the future relies on a diversified grid.

### Tidal and Wave Energy
The oceans represent a massive, untapped kinetic energy reserve. New floating turbine designs are finally making tidal energy commercially viable, providing predictable baseline power.

### Green Hydrogen
Created by splitting water using renewable electricity, green hydrogen can act as a high-density energy carrier, perfect for decarbonizing heavy industries like steel manufacturing and shipping.

### Space-Based Solar Power
Currently in the testing phase, satellites equipped with massive solar arrays could beam gigawatts of uninterrupted power back to Earth via microwaves, completely bypassing the intermittency issues of terrestrial solar.

## Conclusion
The grid of the future will be decentralized, multi-modal, and entirely carbon-free.
    `,
    category: 'Renewable Energy',
    author: { name: 'Dr. Sarah Jenkins', avatar: 'https://i.pravatar.cc/150?u=sarah', role: 'Climate Scientist' },
    readTime: '9 min',
    views: '11.2K',
    publishDate: '2026-06-14',
    imageUrl: 'https://images.unsplash.com/photo-1466611653911-95081537e5b7?w=800&q=80',
    featured: true,
    trending: true,
    tags: ['Energy', 'Solar', 'Future']
  },
  {
    id: '6',
    slug: 'climate-change-facts-and-solutions',
    title: 'Climate Change Facts and Solutions',
    summary: 'Separating myth from reality: The hard data on climate change and the actionable solutions we have today.',
    content: `
## The Hard Facts

- **Temperature Rise:** The Earth's average surface temperature has risen by about 2.12 degrees Fahrenheit (1.18 degrees Celsius) since the late 19th century.
- **Warming Oceans:** The oceans have absorbed much of this increased heat, with the top 100 meters showing warming of more than 0.6 degrees Fahrenheit since 1969.
- **Shrinking Ice Sheets:** The Greenland and Antarctic ice sheets have decreased in mass. Data from NASA shows Greenland lost an average of 279 billion tons of ice per year between 1993 and 2019.

## Solutions We Can Implement Now

1. **Reforestation:** Planting trees remains one of the most cost-effective methods of drawing down carbon.
2. **Shift to Circular Economies:** Moving away from single-use plastics and planned obsolescence.
3. **Decarbonizing Transportation:** Accelerating the adoption of EVs and expanding public transit networks.

## THADAM's Role
By giving users a personal Carbon Score, we are democratizing climate action, proving that millions of small actions can shift the global trajectory.
    `,
    category: 'Climate Change',
    author: { name: 'Elena Rostova', avatar: 'https://i.pravatar.cc/150?u=elena', role: 'Researcher' },
    readTime: '8 min',
    views: '9.3K',
    publishDate: '2026-06-05',
    imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?w=800&q=80',
    featured: false,
    trending: false,
    tags: ['Facts', 'Science', 'Action']
  },
  {
    id: '7',
    slug: 'electric-vehicles-and-sustainability',
    title: 'Electric Vehicles and Sustainability',
    summary: 'Are EVs truly green? We examine the lifecycle emissions of electric vehicles from production to recycling.',
    content: `
## The EV Debate

Electric Vehicles produce zero tailpipe emissions, but critics often point to the carbon-intensive manufacturing process, specifically battery production.

## Lifecycle Emissions Analysis

Studies consistently show that even when factoring in the manufacturing process and the current fossil-fuel heavy energy grid, an EV's lifetime emissions are significantly lower than an Internal Combustion Engine (ICE) vehicle. 

- **Manufacturing:** EV production emits roughly 15-68% more carbon than an ICE vehicle.
- **Operation:** An EV "breaks even" on its carbon debt after roughly 15,000 to 20,000 miles of driving.
- **End of Life:** The recycling of lithium-ion batteries is rapidly improving. Companies like Redwood Materials are now recovering up to 95% of key battery elements like cobalt, nickel, and lithium.

## The Verdict
EVs are not a silver bullet—active mobility (walking, cycling) is always better—but they are an absolute necessity for decarbonizing our transport sector.
    `,
    category: 'Electric Vehicles',
    author: { name: 'Alex Rivera', avatar: 'https://i.pravatar.cc/150?u=alex', role: 'Automotive Journalist' },
    readTime: '6 min',
    views: '14.1K',
    publishDate: '2026-06-09',
    imageUrl: 'https://images.unsplash.com/photo-1593941707882-a5bba14938cb?w=800&q=80',
    featured: true,
    trending: true,
    tags: ['EV', 'Transport', 'Battery']
  },
  {
    id: '8',
    slug: 'circular-economy-explained',
    title: 'Circular Economy Explained',
    summary: 'Why the take-make-dispose model is dying, and how a circular economy aims to eliminate waste entirely.',
    content: `
## The Linear Problem

Since the industrial revolution, our economy has been linear: we extract raw materials, make products, use them briefly, and throw them away. This model assumes infinite resources and infinite disposal capacity—both of which are false.

## The Circular Solution

A circular economy rests on three principles:
1. **Design out waste and pollution:** Products are designed from the outset to be disassembled and reused.
2. **Keep products and materials in use:** Through repair, refurbishment, and remanufacturing.
3. **Regenerate natural systems:** Returning valuable nutrients to the soil rather than putting them in a landfill.

## THADAM's Ecosystem
THADAM is built purely on circular principles. Our platform connects consumers, recyclers, and producers, ensuring that a plastic bottle is never "waste" but rather a "resource in transit."
    `,
    category: 'Circular Economy',
    author: { name: 'David Okafor', avatar: 'https://i.pravatar.cc/150?u=david', role: 'Sustainability Consultant' },
    readTime: '7 min',
    views: '15.3K',
    publishDate: '2026-06-13',
    imageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=800&q=80',
    featured: false,
    trending: true,
    tags: ['Economy', 'Recycling', 'Future']
  },
  {
    id: '9',
    slug: 'ai-for-sustainability',
    title: 'AI for Sustainability',
    summary: 'How artificial intelligence is mapping deforestation, predicting climate disasters, and optimizing global supply chains.',
    content: `
## AI: The Ultimate Climate Tool

Artificial Intelligence is uniquely suited to handle the massive datasets inherent in climate science.

### Deforestation Mapping
Machine learning models analyze satellite imagery in real-time to detect illegal logging activities in the Amazon, alerting authorities before major damage is done.

### Precision Agriculture
AI systems process soil data, weather forecasts, and crop imagery to tell farmers exactly when to water and fertilize, drastically reducing water usage and nitrogen runoff.

### Grid Optimization
AI predicts energy demand and seamlessly balances the grid, ensuring that intermittent renewable sources like wind and solar are utilized with maximum efficiency.
    `,
    category: 'AI for Sustainability',
    author: { name: 'Michael Chen', avatar: 'https://i.pravatar.cc/150?u=mike', role: 'AI Researcher' },
    readTime: '8 min',
    views: '8.2K',
    publishDate: '2026-06-12',
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80',
    featured: true,
    trending: true,
    tags: ['AI', 'Innovation', 'Technology']
  },
  {
    id: '10',
    slug: 'how-thadam-uses-ai-for-climate-action',
    title: 'How THADAM Uses AI for Climate Action',
    summary: 'A deep technical dive into how THADAM integrates Gemini 1.5 Pro and Vision to create a personalized sustainability experience.',
    content: `
## The THADAM Architecture

THADAM isn't just an app; it is a highly integrated AI ecosystem designed to eliminate the friction from sustainable living.

### 1. The Carbon Twin AI
Powered by Gemini 1.5 Pro, the Carbon Twin acts as your personal climate coach. It doesn't just give generic advice; it analyzes your specific habits, local weather patterns, and regional recycling rules to provide hyper-personalized, actionable tasks.

### 2. The Waste Scanner
Using Gemini Vision, our edge-enabled scanner allows users to point their camera at any piece of waste. The AI instantly identifies the material composition, checks local recycling compatibility, and instructs the user on exactly which bin to use.

### 3. Smart Machine Integration
When you deposit items into a THADAM Smart Bin, the internal AI verifies the material, preventing contamination. It then securely syncs with Firebase to instantly update your reward points and carbon score.

## The Result
By combining elite AI reasoning with gamified mechanics, THADAM transforms sustainability from a chore into a rewarding daily habit.
    `,
    category: 'AI for Sustainability',
    author: { name: 'THADAM Engineering', avatar: 'https://i.pravatar.cc/150?u=thadam', role: 'Core Team' },
    readTime: '6 min',
    views: '22.1K',
    publishDate: '2026-06-14',
    imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?w=800&q=80',
    featured: true,
    trending: true,
    tags: ['THADAM', 'Gemini', 'Vision']
  }
];

const MOCK_IMAGES = [
  'photo-1542601906990-b4d3fb778b09',
  'photo-1508514177221-188b1cf16e9d',
  'photo-1473341304170-971dccb5ac1e',
  'photo-1466611653911-95081537e5b7',
  'photo-1509391366360-2e959784a276',
  'photo-1532996122724-e3c354a0b15b',
  'photo-1497366216548-37526070297c',
  'photo-1501854140801-50d01698950b',
  'photo-1447752875215-b2761acb3c5d',
  'photo-1470071459604-3b5ec3a7fe05',
  'photo-1500485035595-cbe6f645feb1',
  'photo-1513836279014-a89f7a76ae86',
  'photo-1441974231531-c6227db76b6e',
  'photo-1507525428034-b723cf961d3e'
];

// Add 10 more mock articles to reach the 20+ requirement
for (let i = 11; i <= 24; i++) {
  const imageId = MOCK_IMAGES[(i - 11) % MOCK_IMAGES.length];
  BLOG_POSTS.push({
    id: i.toString(),
    slug: `sample-article-${i}`,
    title: `Exploring Environmental Dynamics Part ${i}`,
    summary: `A comprehensive look into sustainable practices and modern innovations in chapter ${i} of our ongoing series.`,
    content: `## Overview \n\nThis is a sample generated article to demonstrate the scale of the THADAM knowledge base. \n\n### Key Takeaways\n- Sustainability is crucial.\n- Technology plays a major role.\n- Every action counts.`,
    category: CATEGORIES[i % CATEGORIES.length].name,
    author: { name: 'Guest Contributor', avatar: `https://i.pravatar.cc/150?u=${i}`, role: 'Writer' },
    readTime: '4 min',
    views: `${((i * 1.7) % 9 + 1).toFixed(1)}K`,
    publishDate: '2026-06-01',
    imageUrl: `https://images.unsplash.com/${imageId}?w=800&q=80`,
    featured: false,
    trending: i % 3 === 0,
    tags: ['Sample', 'Environment']
  });
}
